#!/usr/bin/env bash

rm -f -R builddir/ && 

meson setup builddir && cd builddir && ninja && cd .. &&


if [ -f "$(which meson-init-cpp)" ]; then
  read -p "Already installed. Do you want to uninstall it? (y/n): " choice
  if [ "$choice" == "y" ]; then
    if [ "$(id -u)" == 0 ]; then
      rm -f -R "$(which meson-init-cpp)"
    elif command -v sudo &> /dev/null; then
      sudo rm -f -R "$(which meson-init-cpp)"
    elif command -v doas &> /dev/null; then
      doas rm -f -R "$(which meson-init-cpp)"
    fi
  fi
else
  read -p "Do you want to install meson-init-cpp? (y/n): " installchoice
  if [ "$installchoice" == "y" ]; then
    if [ "$(id -u)" == 0 ]; then
     cp ./builddir/meson_init_cpp /usr/local/bin/meson-init-cpp
    elif command -v sudo &> /dev/null; then
      sudo cp ./builddir/meson_init_cpp /usr/local/bin/meson-init-cpp
    elif command -v doas &> /dev/null; then
      doas cp ./builddir/meson_init_cpp /usr/local/bin/meson-init-cpp
    fi
  fi
fi

