name: Install Mesa and Run


on:
 pull_request:
 workflow_dispatch:
 push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Meson
        run: sudo apt-get install meson build-essential

      - name: Run bash script
        run: make
      - name: Test if correct version
        run: mkdir test && cd test && meson-init-cpp foo 0.1 14 && make && ./builddir/foo && cd ../.. && rm -rf test/
      - name: Test if version is incorrect
        run: mkdir test && cd test && meson-init-cpp 0.1 3000 && make
