name: Install Mesa and Run


on:
 pull_request:
 workflow_dispatch:
 push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Mesa
        run: sudo apt-get install meson build-essential

      - name: Run bash script
        run: bash run
