name: Install Mesa and Run


on:
 pull_request:
 workflow_dispatch:
 push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Meson
        run: sudo apt-get install meson build-essential

      - name: compile
        run: make
      - name: install
        run: sudo make install
      - name: clean directory
        run: sudo rm -rf /tmp/test /tmp_incorrect
      - name: Test if correct version
        run: cd $(mktemp -d) && meson-init-cpp foo 0.1 14 && make && ./builddir/foo 
      - name: Test if version is incorrect
        run: cd $(mktemp -d)&& meson-init-cpp foo 0.1 3000 && make && exit 0
